### ISSUE TITLE
Missing file "utils.py"

### ISSUE THREAD

**Issue by hjames1** [almaan/her2st#1]
Hello, thanks for sharing. 

However, the "utils.py" file which contains "bean_plot" function is not included in the folder. 

By the way, the following files do not seem to be uploaded successfully.

```
correlation.py
cluster.py
add-tme.py
visualize-tme.py
corrsearch.py
funcs.py
utils.py
convert-to-loompy.py
update-files.py
update-namemap.py
```

Can you check? Thanks.

**Comment by almaan** [comment]
Hello @hjames1, thank you for your comment and making me aware of this. It seems like I accidentally added the `utils.py` file to the `.gitignore` file - this is now taken care of `utils.py` is a part of the repo. 

I don't think the other files you list are used for any of the analyses in the manuscript, but rather represent ideas that we chose to not pursue any further. I could share them of course, but don't want to make the repo cluttered with things that aren't relevant. However, I could put them up on a different branch if you're really keen to access them, is there a particular reason as to why you request these files as well?

Best,
Alma

**Comment by hjames1** [comment]
Thanks for your quick reply! If other documents are not relevant to the manuscript, then I don't need them.

**Comment by hjames1** [comment]
By the way, some other files generated by stereoscope are also missing (^W files in./res/ST-deconv/props)

Can you check please ?

**Comment by almaan** [comment]
@hjames1 , which proportion files are missing? As far as I can see the `zip` files containing the proportion estimates of all cell types are there. These files are, for clarity, no longer named `W*tsv` but rather `[patient][section]-proportion.tsv` and are found in the aforementioned zip files (named: `major.zip`, `minor.zip`, and `subset.zip`.

Best,
Alma

**Comment by hjames1** [comment]
@almaan , thanks a lot, now `corrplot.r` script is now running smoothly according to your hints.

**Comment by almaan** [comment]
@hjames1 , great - if you feel as if your questions have been answered, feel free to close this issue :)

**Comment by hjames1** [comment]
@almaan , OK, I'll close this issue  :)

**Comment by hjames1** [comment]
@almaan  OK, I'll close this issue :)
