### ISSUE TITLE
High resolution spatial transcriptomics images 

### ISSUE THREAD

**Issue by KalinNonchev** [almaan/her2st#4]
Hello,

I have been unable to locate the high-resolution .TIF images for the samples mentioned in your paper.
The images provided on the following website (https://zenodo.org/record/4751624#.ZFs1JC9BzRY) are of low resolution.

Therefore, I would like to request if you could kindly share the high-quality resolution images with me.

Thank you in advance!

Best,

**Comment by KalinNonchev** [comment]
@almaan @ludvigla maybe you can help here?

**Comment by KalinNonchev** [comment]
what is also the spot diameter?

**Comment by KalinNonchev** [comment]
@almaan @ludvigla

**Comment by almaan** [comment]
Hi @KalinNonchev , if you read the first paragraph of the "Method" section in the associated paper, you'll find the following information:

`The microarrays were generated as a 33 × 35 grid of printed spots with a 200 μm center-to-center distance of 100 μm between each capture location (spot). A total of 1007 spots were printed with unique DNA oligonucleotides (spatial barcodes) attached to oligo(dT) capture probes.`

which I believe answers your question about the spot diameter. As for the full-size images, we're happy to share them with you, however, the person conducting the experiments has left the group (and so have I, meaning I no longer have access to any stored data) - Ludvig will attempt to locate them on our server and answer your email, it might take a while though.

Best,
Alma

**Comment by KalinNonchev** [comment]
Yeah, I found this section later. Thank you for the help.
Great! Then I will be waiting for a replay from Ludvig.

Best,

**Comment by YuyanRuan** [comment]
@almaan Hi Alma! Would you please email me the high-resolution images as well? Thank you very much!
My email is yruanaf@connect.ust.hk

**Comment by ludvigla** [comment]
Hey guys, 

Sorry for the late reply. The images I have access to are the ones that we provide in this GitHub repo. I will check with Linnea Stenbeck who ran the experiments if she can provide the images in higher resolution, but the data was generated in 2016 and I'm not sure if the original TIF files were saved. If anyone have the images, that would be her though. I'll get back to you if I can get my hands on the images but it might take some time.

Cheers,
Ludvig

**Comment by YuyanRuan** [comment]
Sure, thanks a lot for sharing the great resources!!!

**Comment by KalinNonchev** [comment]
Thank you for the input @ludvigla, hope they still exist somewhere. The uploaded here are getting pixelated fast when zoomed.

**Comment by KalinNonchev** [comment]
any news? @ludvigla

**Comment by KalinNonchev** [comment]
I am closing thin since high-resolution images were not available.
